<?php

/**
* Implements hook_install().
*/
function test_d7_install() {
  drupal_install_schema('test_d7');
}

/**
* Implements hook_schema().
*/
function test_d7_schema() {
  $schema = array();

  $schema['test_form_data'] = array(
    'description' => t('Stores some user data.'),
    'fields' => array(
      'id' => array(
        'description' => t('The primary key for each user'),
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'first_name' => array(
        'description' => t('First Name'),
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
      'last_name' => array(
        'description' => t('Last Name'),
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
      'phone' => array(
        'description' => t('Phone number'),
        'type' => 'varchar',
        'length' => 80,
        'not null' => FALSE,
        'default' => '',
      ),
      'email' => array(
        'description' => t('Email address'),
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
      'username' => array(
        'description' => t('Username'),
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
      'password' => array(
          'description' => t('Password'),
          'type' => 'varchar',
          'length' => 80,
          'not null' => TRUE,
          'default' => '',
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'email' => array('email'),
    ),
  );

  return $schema;
}

