<?php

/**
* Implements hook_install().
*/
function test_d7_install() {
  drupal_install_schema('test_d7');
}

/**
* Implements hook_schema().
*/
function test_d7_schema() {
  $schema = array();

  $schema['test_form_data'] = array(
    'description' => t('Stores some user data.'),
    'fields' => array(
      'id' => array(
        'description' => t('The primary key for each user'),
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'email' => array(
        'description' => 'Email address.',
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
      'username' => array(
        'description' => 'Username',
        'type' => 'varchar',
        'length' => 80,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'email' => array('email'),
    ),
  );

  return $schema;
}
